apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sudoku-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sudoku-game
  template:
    metadata:
      labels:
        app: my-sudoku-game
    spec:
      containers:
      - name: my-sudoku-game
        image: testapp01.azurecr.io/my-sudoku-game:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: my-sudoku-game
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: my-sudoku-game
